# Generated by Django 5.1.5 on 2025-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurante",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
