# Generated by Django 5.1.5 on 2025-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="apellido",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
