# Generated by Django 5.1.5 on 2025-03-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fichaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrada", models.DateTimeField()),
                ("fecha_salida", models.DateTimeField(blank=True, null=True)),
                ("duracion", models.DurationField(blank=True, null=True)),
                ("automatica", models.BooleanField(default=False)),
                ("incidencia", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
