# Generated by Django 5.1.5 on 2025-03-11 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fichajes", "0001_initial"),
        ("restaurantes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaje",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fichajes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fichaje",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restaurante",
            ),
        ),
    ]
