# Generated by Django 5.1.5 on 2025-03-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichajes", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contrasenia_panel", models.CharField(max_length=100)),
            ],
        ),
    ]
