# Generated by Django 5.1.5 on 2025-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichajes", "0003_configuracionacceso"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaje",
            name="compensado",
            field=models.BooleanField(default=False),
        ),
    ]
