# Generated by Django 5.1.5 on 2025-03-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichajes", "0005_resumenmensual"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correo_destino",
                    models.EmailField(
                        max_length=254, verbose_name="Correo para backups"
                    ),
                ),
            ],
        ),
    ]
